// <auto-generated />
using BankOfSimba.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankOfSimba.Migrations
{
    [DbContext(typeof(BankOfSimbaDbContext))]
    [Migration("20200420070450_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankOfSimba.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnimalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalType = "lion",
                            Balance = 2000m,
                            Name = "Simba"
                        },
                        new
                        {
                            Id = 2,
                            AnimalType = "elephant",
                            Balance = 5000m,
                            Name = "Hathi"
                        },
                        new
                        {
                            Id = 3,
                            AnimalType = "wolf",
                            Balance = 6000m,
                            Name = "Akela"
                        },
                        new
                        {
                            Id = 4,
                            AnimalType = "bear",
                            Balance = 1000m,
                            Name = "Balu"
                        },
                        new
                        {
                            Id = 5,
                            AnimalType = "snike",
                            Balance = 500m,
                            Name = "Ka"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
